### ISSUE TITLE
[BUG] Discussionが有効化されていない

### ISSUE THREAD

**Issue by noko1024** [kqnade/CHaserLua-archive#31]
### Pre-checks

- [X] I have searched the [issues](https://github.com/kqnade/CHaserLua/issues) of this repository and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://github.com/kqnade/CHaserLua/readme.md) and believe that my question is not covered.
- [X] I have searched the [Wiki](https;//github.com/kqnade/CHaserLua/wiki) and believe that my question is not covered.

**Comment by kqnade** [comment]
仕様です
